package io.flutter.plugins;


import io.flutter.app.FlutterActivity;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
public final class GeneratedPluginRegistrantEdit {
  public static void registerWith(FlutterActivity flutterEngine) {
  }
}
